### ISSUE TITLE
Incorrect dependency name in README

### ISSUE THREAD

**Issue by gha3mi** [fortran-lang/http-client#50]
Thank you for the project.

I noticed a small issue in the README file. The name of the dependency is currently listed as `fhash`, but it should be `http`:

```toml
[dependencies]
http = { git = "https://github.com/fortran-lang/http-client.git" }
stdlib = "*"
```

`stdlib = "*"` is mentioned in another issue.
